title: Kavinila VG
logo: /assets/img/my_profile.jpeg
description: 
description:
  <a href="https://github.com/kavinila-vg">GitHub</a>
  
  <br>   
  I'm working on Chatbots, Machine learning & NLP related problems.
  Worked in IBM and Azure cloud services.
  Working in Drug repurposing and related research.
  <br>

theme: jekyll-theme-minimal
