title:  <p align="center">Kavinila VG</p>
logo: /assets/img/logo.png
description: 
description:

  <p align="center">
  <a href="https://github.com/kavinila-vg">GitHub</a>
  
  <br>   
  I'm working on Chatbots, Machine learning & NLP related problems.
  Worked in IBM and Azure cloud services.
  Working in Drug repurposing and related research.
  <br>
  </p>

theme: jekyll-theme-minimal
